### ISSUE TITLE
wrong number of arguments (1 for 3) on CombinePDF.parse

### ISSUE THREAD

**Issue by podsi** [boazsegev/combine_pdf#127] opened 2017-09-28 12:26 UTC
I'm getting the following exception when calling `CombinePDF.parse( content )`:

```
"...../.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/pdf_protected.rb:305:in `hash_merge_new_no_page'",
 "org/jruby/RubyHash.java:1712:in `merge!'",
 "...../.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/pdf_public.rb:305:in `insert'",
 "...../.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/pdf_public.rb:278:in `<<'",
.......
```

**Comment by boazsegev** [comment] 2017-09-28 12:35
Hi @podsi ,

Thank you for opening this issue! 🙏🏻

Could you send me an example PDF so I can recreate the issue?

Also, does this happen exclusively on JRuby or does it fail on Ruby MRI as well?

Kindly,
   Bo.

**Comment by podsi** [comment] 2017-09-28 13:56
Hi @boazsegev ,

thx for reply! 👍 

Doesn't matter which PDF or if you use Ruby or JRuby, it's kind of the same issue, but with Ruby it's calling `hash_update_proc_for_old`. Perhaps I made a mistake in my code example, but with this example you will get the error `wrong number of arguments (1 for 3)`, I tried it with both, Ruby & JRuby (I attached the `Test.pdf`):

```
require 'combine_pdf'

f = IO.read( "./Test.pdf" )

pdf = CombinePDF.new
pdf << CombinePDF.parse( f )
```
[Test.pdf](https://github.com/boazsegev/combine_pdf/files/1341129/Test.pdf)

**Comment by boazsegev** [comment] 2017-09-28 14:15
Hi @podsi 

Sorry, I can't replicate the issue.

Could you post the system you're running on?

I'm running Ruby 2.4.1 on my macOS (Sierra) with a MacBook Pro.

As a sidenote, consider using `load` instead of `IO.read` (or at least change to `IO.binread`, since PDF are binary files). i.e.:

```ruby
require 'combine_pdf'
pdf = CombinePDF.new
pdf << CombinePDF.load( "./Test.pdf" )
```

Another thought I had, because one of the line numbers in the error message doesn't match the code, is that it might be a gem installation issue (maybe files from old and new gem versions god mixed up or manual changes were made)... 

Consider removing and reinstalling the gem.

Let me know if anything changes.

B.

**Comment by podsi** [comment] 2017-09-29 06:35
Hi @boazsegev 

I'm sorry, I did a mistake. Forgot that it's still calling jruby, when I call `ruby test.rb` in my jruby project directory, so it's just failing on jruby, maybe I should give it try to update my jruby version to the latest.

I'm running JRuby 9.1.6.0 (Ruby 2.3.1) on my macOS (Sierra) MacBook Pro.

```
$ ruby --version
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.101-b13 on 1.8.0_101-b13 +jit [darwin-x86_64]
$ ruby test.rb
ArgumentError: wrong number of arguments (1 for 3)
  hash_update_proc_for_old at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/parser.rb:520
                    merge! at org/jruby/RubyHash.java:1712
             catalog_pages at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/parser.rb:520
             catalog_pages at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/parser.rb:485
    block in catalog_pages at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/parser.rb:481
                      each at org/jruby/RubyArray.java:1734
             catalog_pages at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/parser.rb:481
             catalog_pages at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/parser.rb:539
             catalog_pages at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/parser.rb:485
             catalog_pages at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/parser.rb:549
                     parse at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/parser.rb:167
                initialize at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/pdf_public.rb:94
                      load at /Users/podsi/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/combine_pdf-1.0.7/lib/combine_pdf/api.rb:11
                    <main> at test.rb:3
```

But if I run it in my home directory with `Ruby 2.2.3p173` it's working.
```
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
```

Maybe this helps. 😉

**Comment by boazsegev** [comment] 2017-09-29 12:55
Hi @podsi ,

Thank you for letting me know, since this helps me track down the issue.

I'll try to work on this later this weekend, but for now I suspect this might be a JRuby issue, where JRuby calls the `block` passed to `merge` using a single argument instead of three.

Please let me know if updating the JRuby version helps.

Kindly,
  B.

**Comment by boazsegev** [comment] 2017-10-02 03:34
Hi @podsi ,

I've has some issues trying to install the JDK on my Mac.

Could you let me know if installing the new JRuby fix the issue?

Kindly,
   Bo.

**Comment by xiaoweiliu945** [comment] 2017-11-03 21:48
For me, I use jruby 9.1.13.0, got almost the same problem with @podsi.

This problem starts from the version 0.2.34, so currently I use 0.2.33.

There are some modification on parse.rb for 0.2.34, might be the cause of this problem.

Just provide some hint, still haven't figure it out.

Thanks for your support, @boazsegev 

Kindly
Xiaowei

**Comment by boazsegev** [comment] 2017-11-08 01:58
@xiaoweiliu945 , thank you for your input.

I'm fairly certain this is an issue in the JRuby interpreter, since Ruby should be sending 3 arguments to the Hash Proc (and not just 1 argument)...

...However, I tried writing a workaround, since I think the issue might be caused by the use of a detached method rather than a regular Proc object. I can't test it on my machine (I can't install JRuby for some reason).

If you have time to test it out with the Github version of the gem, I would appreciate it.

Bo.

**Comment by bolandross** [comment] 2018-08-12 11:31
Hey Bo!

First I want to thank you for the work that you have put in this helpful project.

Since I would like to use combine_pdf in my JRuby project, too, I thought it might be good idea to chime in.

It seems like the problem still exists in JRuby 9.2.0.0

When trying to make the simple combine example run, it gives me the following details:

`Exception in thread "JavaFX Application Thread" org.jruby.exceptions.ArgumentError: (ArgumentError) wrong number of arguments (1 for 3)
	at RUBY.hash_merge_new_no_page(/usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/combine_pdf-1.0.14/lib/combine_pdf/pdf_protected.rb:309)
	at org.jruby.RubyHash.merge!(org/jruby/RubyHash.java:1876)
	at RUBY.insert(/usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/combine_pdf-1.0.14/lib/combine_pdf/pdf_public.rb:309)
	at RUBY.<<(/usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/combine_pdf-1.0.14/lib/combine_pdf/pdf_public.rb:282)`

Is there a workaround that I could use in JRuby?

In the comments, you mention "one way to combine". Are there maybe other ways, that are less problematic?

`pdf = CombinePDF.new`
`pdf << CombinePDF.load("file1.pdf") # one way to combine, very fast.`
`pdf << CombinePDF.load("file2.pdf")`
`pdf.save "combined.pdf"`

Best regards
Ben

**Comment by boazsegev** [comment] 2018-08-12 12:18
Hi Ben ( @bolandross ),

Thank you for joining the discussion.

> It seems like the problem still exists in JRuby 9.2.0.0

I'm sad to read that JRuby 9.2.0.0 still has incompatibility issues with Ruby MRI.

I really think this is a JRuby issue that should be reported and resolved on their side.

> Is there a workaround that I could use in JRuby?

Not that I can think of. The internal implementation (no matter which API you use) will end up calling `Hash.merge` with a block used for resolving conflicts `hash_merge_new_no_page`.

The fact that JRuby calls the block with less than 3 arguments is the reason the call breaks (perhaps having the last argument as `nil` causes that issue).

I've made another stab at working around the issue, with version 1.0.15... but I doubt if it will work.

Kindly,
B.

**Comment by boazsegev** [comment] 2018-08-13 16:43
@bolandross ,

Please lee me know if the new release solves the JRuby compatibility issue.

Kindly,
  B.

**Comment by bolandross** [comment] 2018-08-13 17:33
@boazsegev ,
Thanks for your response!
Since I'm quite a novice regarding this topic, would you mind reporting the problem to the JRuby guys? I think that they have a issue section on their Github project, too. I would love to be able to use combine_pdf with JRuby.

Best regards,
Ben

**Comment by boazsegev** [comment] 2018-08-14 14:58
@bolandross 

I understand you installed version 1.0.15 and still get the same error?

B.

**Comment by bolandross** [comment] 2018-08-14 15:03
@boazsegev 
Sorry, it seems like there was a misunderstanding!
As soon as I'll be back home today, I will test your version 1.0.15 with JRuby 9.2.0.0 and give you feedback asap.

Best regards
Ben

**Comment by bolandross** [comment] 2018-08-14 15:59
@boazsegev 
I came here to report that it now works!! 👍 
Thank you very much :D

**Comment by boazsegev** [comment] 2018-08-14 18:06
@bolandross ,

Thanks for the update. I'm happy the workaround I implemented worked 🎉

Kindly,
   Bo.

**Closed by boazsegev** 2018-08-14 18:06 UTC
Labels: can't reproduce, compatibility
