### ISSUE TITLE
Malformed PDF file

### ISSUE THREAD

**Issue by rafagf1** [boazsegev/combine_pdf#126] opened 2017-09-22 11:30 UTC
Hi

I am trying to load a pdf and after several messages "Warning: parser advancing for unknown reason. Potential data-loss" shows me the error "Unknown PDF parsing error - malformed PDF file?"

PDF looks correct, such as PDF opens properly in chrome.

Where can I send the pdf without it being published in github?

I'm using combine_pdf (1.0.7)

Thanks for your time.

**Comment by boazsegev** [comment] 2017-09-22 13:33
Hi @rafagf1 ,

Thank you for opening this issue.

Please free to email me the PDF file. I don't add any of the PDF files I get for testing to the Repo.

Kindly,
   Bo.

**Comment by boazsegev** [comment] 2017-09-25 11:14
Hi @rafagf1,

Just a quick update:

I found the cause that breaks the parses... it seems the PDF is actually malformed.

In line 5 of the PDF file, there's a String opening first character `(` that never closes (parenthesis is one way to indicate PDF data strings, almost like quotation marks in Ruby). I can't believe it took me so long to notice it. Sorry about that.

I'm not sure what's the best way to deal with this PDF error.

Unlike some binary parsers, CombinePDF parses the PDF top to bottom (instead of using the binary map at the end of the file). This allows CombinePDF to completely and linearly deconstruct a PDF file is a way that is fairly efficient in Ruby (as well as minimize CPU cache misses where allowed by the Ruby layer).

However, it also means that it's harder to recuperate from PDF errors, since a single broken object will corrupt all the following data (and not just that object's data).

I'm still looking into this, since I hope to find a workaround that will help the parser handle more PDF errors - but I no longer consider this a bug.

Kindly,
  B.

**Comment by rafagf1** [comment] 2017-09-26 06:47
These are the first lines of the PDF:

% PDF-1.1 ^ M
1 0 obj ^ M
<< ^ M
/ Creator (Developer 2000) ^ M
/ CreatorDate (^ M
/ Author (Oracle Reports) ^ M
/ Producer (Oracle PDF driver)

I imagine the bug is by the line of "CreatorDate"

Could you discard headers that aren't mandatory and are not well-formed?

Thanks

**Comment by boazsegev** [comment] 2017-09-26 11:18
You're right, the issue is the `/CreatorDate (` line.

It is followed by the `"\r\n"` control characters, which are both allowed within a PDF string literal.

The next line includes allowable characters as well as a balanced parenthesis (`(...)`), which are all allowed.

There doesn't seem to be any point at which I can safely tell the parser "this indicates an error".

In fact, by the time the string literal closes, the parser is halfway through the file reading binary font data.

If there were any illegal characters anywhere in the middle, the String literal would have probably been skipped and the parser would have limited the corruption to the `1 0 obj` object (the parser wouldn't recognize the string literal if it had illegal characters, causing the symbol-value hash object to be incorrectly paired)...

...This a combination of poor luck as well as a malformed PDF, since a different font file might have contained an illegal character before the closing parenthesis, helping the parser catch the error.

The only solution I can think of is file specific (not relevant to other files).

```ruby
tmp = IO.binread("path/to/original.pdf")
tmp.sub! "/CreatorDate (", "/CreatorDat ()" # string length must never change
pdf = CombinePDF.parse tmp
pdf.save "path/to/fixed.pdf"
```

I know this isn't a solution at all, but I can't seem to think of any other ideas.

**Comment by rafagf1** [comment] 2017-09-28 07:18
For this particular pdf would work, the problem is that I get many pdfs that are not 100% well formed, for example some are missing 'endobj' and combined_pdf shows me the warnings.

Example: "'endobj' keyword was missing for Object ID: 33, trying to auto-fix issue, but might fail"

In some cases nothing happens, but in others some of the information is lost.

All of these pdfs are correctly viewed in various pdf viewers.

Would there be any way to correct these pdf faults (even with another gem) before using combine_pdf?

Thanks

**Comment by boazsegev** [comment] 2017-09-28 12:32
> the problem is that I get many pdfs that are not 100% well formed...

I'm sorry that this is the case. I wonder why that is and hope it changes with time.

I tried my best to have the parser recuperate from as many PDF errors as I could manage without mis-reading conforming PDF files.

> Would there be any way to correct these pdf faults (even with another gem) before using combine_pdf?

Yes, there are gems that are use external (non-Ruby) dependencies, such as iText (java) or `pdftk` that provide binary processing of the PDF, allowing the file to be parsed from the bottom up using the file's binary map.

`pdftk` specifically has a command meant to fix (or attempt to fix) broken PDF files.

Just to name the first to that pop to my head, there are: [pdftk](https://github.com/Nattfodd/pdftk), [pdf-toolkit](https://github.com/blambeau/pdf-toolkit). If you're using JRuby, you can also look into iText.

CombinePDF was meant to provide a pure Ruby solution that would perform on any Ruby platform (otherwise I would have added C bindings, like I did in `iodine`).

**Comment by boazsegev** [comment] 2017-09-28 12:49
I'm closing the issue because I see no way to change the behavior of malformed PDF handling (except, maybe, rewriting the whole gem to use a binary approach, which will probably slow things down and take tons of time to do).

I wish you luck and I'm sorry I couldn't have helped more.

**Closed by boazsegev** 2017-09-28 12:49 UTC

**Comment by rafagf1** [comment] 2017-09-28 14:01
Ok, thanks for your time.
