### ISSUE TITLE
Umlaut handling

### ISSUE THREAD

**Issue by andyentity** [boazsegev/combine_pdf#50] opened 2016-03-04 10:56 UTC
I want to add textboxes to an existing page and everything is working fine, except German special characters are not output correctly.
```
page.textbox("ßöäüÖÄÜ", address_options)
```
becomes
![selection_052](https://cloud.githubusercontent.com/assets/15727344/13525246/1c6aa8c0-e200-11e5-8b1d-9de16386eba1.png)
in the pdf file. Is there some sort of workaround?

**Comment by boazsegev** [comment] 2016-03-04 15:12
Hi @andyentity ,

by design, PDF files are ANSI encoded. This isn't a Ruby thing - **all** PDF files are ANSI encoded.

To allow for Unicode characters, PDF files use character maps (like the old Microsoft Windows systems use to do).

You will need to find (or create) a PDF which maps these special characters find the specific font family using [PDF#fonts](http://www.rubydoc.info/gems/combine_pdf/0.2.16/CombinePDF/PDF#fonts-instance_method) and import that font using the [CombinePDF::Fonts.register_font_from_pdf_object](http://www.rubydoc.info/gems/combine_pdf/0.2.16/CombinePDF/Fonts#register_font_from_pdf_object-class_method) method...

... although, you will be walking the edge of the library's capabilities.

This function is documented as broken since it's right there on the edge and this isn't a simple thing to do.

I've used it to register Hebrew text (see the implementation in the [demo application](https://github.com/boazsegev/combine_pdf_demo/blob/996e3f145b72fa31bc831b441f0cf42021c5e509/pdf_controller.rb#L51-L62)), but this level of PDF editing and PDF Object manipulation wasn't something the CombinePDF library was designed for... I'm guessing that someone with enough knowledge of font files can do better (registering a font from a font file would make this much better).

Anyway, once you have enough fonts (a font family) to cover all your unicode needs, you should set up the `:font` property in the textbox method, to apply the fonts. Pass the Array of fronts you registered if you need to combine a number of fonts for the whole character map (UTF8 to ANSI sometimes requires multiple mapping fonts).

The fallback font is always `Helvetica`.

**Comment by boazsegev** [comment] 2016-03-06 06:59
Hi @andyentity ,

Did the answer solve your issue?

If you need something more, please feel free to write back. I'm closing this issue, but you can still write here.

Good Luck!
Bo.

**Closed by boazsegev** 2016-03-06 06:59 UTC
Labels: question
