### ISSUE TITLE
adding pagenumbers broke PDF generated by convert-jpg-to-pdf.net

### ISSUE THREAD

**Issue by vitstradal** [boazsegev/combine_pdf#34] opened 2015-11-04 19:29 UTC
Hello,

I have problem with PDF generated by `convert-jpg-to-pdf.net` (created not by me, but our users),

Example:

    require "combine_pdf"
    pdf = CombinePDF.load("lena.pdf")
    pdf.number_pages
    pdf.save("lena-pagenumbers.pdf")
   
File `lena-pagenumbers.pdf`is broken and displays empty page. 

BTW: PDFinfo shows "producer":

    pdfinfo lena.pdf|grep Producer
    Producer:       PDFlib Lite 7.0.5p3 (PHP5/Linux-x86_64)
    pdfinfo lena-pagenumbers.pdf|grep Producer
    Producer:       Ruby CombinePDF 0.2.9 Library

How to reproduce:
* chose your favourite `.jpg` (http://www.cs.cmu.edu/~chuck/lennapg/len_std.jpg)
* create pdf via http://www.convert-jpg-to-pdf.net
* use `CombinePDF` to add page numbers (or whatever) and save result
* result will be empty page (but not empty file, file contains original pdf file and somethin probably pagenumbers).

**Comment by boazsegev** [comment] 2015-11-04 19:52
Hi Vitas,

Thank you very much for discovering this issue and pointing it out.

It's now fixed in version 0.2.10 - just released.

**Closed by boazsegev** 2015-11-04 19:52 UTC
Labels: bug

**Comment by boazsegev** [comment] 2015-11-05 01:48
Hi Vitas,

I reproduced the issue on my computer and the fix works for me. Could you make sure the fix works for you?

**Comment by vitstradal** [comment] 2015-11-05 08:36
Hi,
yes, it works now, thank you!
