### ISSUE TITLE
Loss of form data when saving PDF 

### ISSUE THREAD

**Issue by joshirashmics** [boazsegev/combine_pdf#115] opened 2017-07-07 03:24 UTC
I am trying to parse pdf file data sent through the html equivalent of a pdf generated through [this tool](https://www.idrsolutions.com/online-pdf-to-html5-converter/). However the pdf that is saved after parsing does not include the data that was filled in the front end. I am attaching the file that was sent ,
[file_sent2.zip](https://github.com/boazsegev/combine_pdf/files/1129937/file_sent2.zip)
(extension changed to zip , because git didn't allow me upload without an extension )

 and also the pdf file that was saved after parsing through combine pdf.
[saved.pdf](https://github.com/boazsegev/combine_pdf/files/1129911/saved.pdf) Here are the couple

 of lines of code that I used to do this.
```
pdf = CombinePDF.parse Base64.decode64(params[:pdfdata])
pdf.save "saved.pdf"
```
The file_send to the server  has values for fields g1145_applicant_petitioner_middle_name and few other fields that I saved in browser , however , the parsed pdf is simply a blank pdf.

**Comment by boazsegev** [comment] 2017-07-07 20:03
Hi @joshirashmics ,

Thank you for opening this issue.

It took me a while to realize that the `file_sent2.zip` is Base64 encoded 😂 sorry about that...

I can confirm the loss of the form data when opening the PDF. I'm on vacation and I'll try to look into it when I can.

B.

**Comment by boazsegev** [comment] 2017-07-07 20:05
P.S.

I'm marking this as `enhancement`, since the README states, under "Known Limitations":

> When reading PDF Forms, some form data might be lost. I tried fixing this to the best of my ability, but I'm not sure it all works just yet.

**Comment by boazsegev** [comment] 2017-07-07 21:10
I narrowed the issue down to PDFs that use Object streams and at the same time they manage versioning by creating objects with identical reference numbers (pointers) instead of updating the reference's version number (PDFs have two identifiers per object, it's ID and it's version)...

CombinePDF should have preferred the latest version, but because of the Object Streams, the ordering was out of wack (and the PDF authoring tool should have updated the reference version, but that's just life, I guess).

Anyway, it might take me a bit of time.

**Closed** 2017-07-07 21:42 UTC
Labels: compatibility, enhancement

**Comment by boazsegev** [comment] 2017-07-07 21:47
I've released a patched version.

I'm afraid the patch might effect performance, since working around the PDF's behavior means I need to grow arrays in the middle rather than the end... add costs include memory copying and shifting as well as increased number of iterations over the parsed PDF data.

I guess this can't be helped, since the moment the PDF didn't use the reference versioning system, it meant CombinePDF couldn't assume the object's order wasn't important for object versions.

Anyway, thanks again for exposing the issue.

**Comment by rachitpant** [comment] 2017-07-09 18:42
Thank You so much for releasing the patch version. Sorry it took me time to get back. I will test and get back.

**Comment by joshirashmics** [comment] 2017-07-09 18:43
Thank You so much for releasing the patch version. Sorry it took me time to get back. I will test and get back.
