### ISSUE TITLE
PDF created with Combine_pdf not working in Preview (Mac)

### ISSUE THREAD

**Issue by mdotslash** [boazsegev/combine_pdf#125] opened 2017-09-13 23:36 UTC
After I build a pdf using the gem, the pdf won't open in Preview app on the mac on my computer. It just hangs and I get the beach ball/loading cursor. 

I also get a similar error when I try to "quick look" in finder.

It shows an error and says "the pdf cannot be previewed."

See image below.

<img width="602" alt="screen shot 2017-09-13 at 4 28 31 pm" src="https://user-images.githubusercontent.com/5124935/30405427-a04efb7a-98a0-11e7-9fae-dedd821a5030.png">

**However, the pdf opens in Adobe Acrobat, Slack, even google drive.**

Any idea if I'm doing something wrong or if it's just a Preview / apple quirk?

I have attached the built pdf below, along with a copy of the script I use:

[new_excerpt.pdf](https://github.com/boazsegev/combine_pdf/files/1301223/new_excerpt.pdf)

Ruby Script (as .txt because I can't upload .rb files) // 

[excerpterPDF.txt](https://github.com/boazsegev/combine_pdf/files/1301229/excerpterPDF.txt)

**Comment by boazsegev** [comment] 2017-09-14 00:41
Hi @mdotslash and thank you for opening this issue.

I downloaded the file and it seems that you're using version 1.0.6.

This might be related to issue #124 which is fixed in version 1.0.7.

Could you test with the updated version and see if the issue persists?

Kindly,
   Bo.

**Comment by boazsegev** [comment] 2017-09-23 03:21
Hi @mdotslash 

Should I close the issue?

**Comment by andyjeffries** [comment] 2020-07-09 15:46
I'm on 1.0.16 and the issue is still present for me.

**Comment by boazsegev** [comment] 2020-07-09 20:41
@andyjeffries ,

I will need an example PDF to replicate the issue. The original file attached to the issue opens on my Mac without any issues.

Kindly,
  Bo.

**Comment by andyjeffries** [comment] 2020-07-10 09:45
I can reproduce it as part of a large proprietary codebase, but can't share the PDFs nor the code that generates them. I've been trying this morning to make a small test script which uses all the features that the main one does, but it always works fine. So frustrating... I'll keep trying and let you know.

**Comment by andyjeffries** [comment] 2020-07-10 09:56
I had one more idea on something I'd missed, but I still can't figure out why I can't reproduce it when I try to isolate it.

However, the test case I tried to create is at https://gist.github.com/andyjeffries/52521551c1bbe4c436d23f7f1babf4f2 in case anyone else running in to this issue can build off my test case with features they're using to try to get a reproducible case.

**Comment by andyjeffries** [comment] 2020-07-10 09:57
If it's of any interest, the "new_excerpt.pdf" linked in the original bug report opens fine for me on macOS Catalina's Preview. That doesn't help me, but may be of interest.

**Comment by boazsegev** [comment] 2020-07-10 11:54
Thanks you @andyjeffries for the updates.

> _If it's of any interest, the "new_excerpt.pdf" linked in the original bug report opens fine for me on macOS Catalina's Preview. That doesn't help me, but may be of interest_.

Actually, it helps, since it shows that this issue is different (not that it's a huge help, but it's something).

> can't share the PDFs

That makes it difficult.

I don't need a result PDF, but a source PDF will help me track down any parsing issues (that may result later on in the issue you experience) as well as allow me to reproduce the issue and test any patches I might come up with.

Without an example PDF and a way to reproduce the issue, I can't test anything and I can't solve it.

> Gist

I left a comment in the Gist.

**Comment by boazsegev** [comment] 2020-07-17 00:21
Does the issue persist with CombinePDF 1.0.17?

**Comment by andyjeffries** [comment] 2020-08-04 20:37
Sorry, took a little time to resurrect those changes back in to my code. By this time 1.0.18 has come and out, and BOOM! It's working perfectly fine. Did you find the bug then?

**Comment by andyjeffries** [comment] 2020-08-04 20:38
Of course I might just be being lucky and you haven't changed anything, but checked a few documents and all of them succeeded.

**Comment by boazsegev** [comment] 2020-08-04 22:53
Hi @andyjeffries ,

Thank you for keeping me posted. I'm happy the patched version works for you.

The issue fixed in the last release was an insidious little devil, and though it effected only a subset of PDF files (depending on the way the PDF was authored), it caused a number of hard to detect side-effects that could eventually corrupt the PDF (see issue #166).

It's possible that this was the issue afflicting you as well.

Anyway, if anything else pops up, please let me know.

Cheers!
   Bo.

**Comment by andyjeffries** [comment] 2020-08-05 07:58
Thank you, will do! 👍

**Closed** 2020-08-05 09:20 UTC
Labels: can't reproduce, waiting for response
