### ISSUE TITLE
 require "combine_pdf" - SyntaxError: /usr/local/rvm/gems/ruby-1.8.7-p374/gems/combine_pdf-1.0.16/lib/combine_pdf/api.rb:11: syntax error, unexpected ':', expecting ')'

### ISSUE THREAD

**Issue by estelleccl** [boazsegev/combine_pdf#161] opened 2019-07-10 02:25 UTC
Hi,

I hit the following error when require "combine_pdf" in the console. What should I do?

Error:-
`SyntaxError: /usr/local/rvm/gems/ruby-1.8.7-p374/gems/combine_pdf-1.0.16/lib/combine_pdf/api.rb:11: syntax error, unexpected ':', expecting ')'
...r.new(IO.read(file_name, mode: 'rb').force_encoding(Encoding...
                              ^
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/combine_pdf-1.0.16/lib/combine_pdf/api.rb:11: syntax error, unexpected ')', expecting kEND
...IO.read(file_name, mode: 'rb').force_encoding(Encoding::ASCI...
                              ^
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/combine_pdf-1.0.16/lib/combine_pdf/api.rb:11: syntax error, unexpected ',', expecting kEND
...ncoding(Encoding::ASCII_8BIT), options))
                              ^
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/combine_pdf-1.0.16/lib/combine_pdf/api.rb:121: odd number list for Hash
    p = { deg: 0, tx: 0, ty: 0, sx: 1, sy: 1 }.merge parameters
              ^
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/combine_pdf-1.0.16/lib/combine_pdf/api.rb:121: syntax error, unexpected ':', expecting '}'
    p = { deg: 0, tx: 0, ty: 0, sx: 1, sy: 1 }.merge parameters
              ^
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/combine_pdf-1.0.16/lib/combine_pdf/api.rb:180: syntax error, unexpected $end, expecting kEND`

**Comment by boazsegev** [comment] 2019-07-10 11:05
Hi @estelleccl,

Thank you for opening the this issue.

The error is probably caused by the fact that you’re using Ruby 1.8.7 (according to the log). Version 1.8.7 is a very old version and it isn’t supported any more (not even by the official Ruby language). 

In fact, [on March 31st, 2019, support for Ruby version 2.3.x has ended](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/). This means you should update to version 2.4.x or higher.

I recommend that you update your Ruby version to the latest stable release.

Let me know if this solves your issue.

Kindly, 
    Bo.

**Comment by boazsegev** [comment] 2019-07-15 00:04
I'm closing this issue. Feel free to open a new issue if you have more questions or encounter any issues.

Kindly,
  Bo.

**Closed by boazsegev** 2019-07-15 00:04 UTC
