### ISSUE TITLE
Merge result might not open on Adobe Reader with error 14

### ISSUE THREAD

**Issue by yul** [boazsegev/combine_pdf#19] opened 2015-04-15 13:56 UTC
File opens in all other readers, but not in Adobe's. Unfortunately, this is the most popular reader.

I was able to fix files with ghostscript (installed in ubuntu server by default I think) with code like this:
```      
      pdf = CombinePDF.new
      files.each do |file|
        pdf << CombinePDF.new(file)
        File.unlink file
      end
      temp_file_name = Rails.root.join('tmp', Dir::Tmpname.make_tmpname(['fwsrp', '.pdf'], nil))
      pdf.save(temp_file_name)
      `gs -o #{file_name} -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress #{temp_file_name}`    # fix corrupt file output
```

This is the ghostscript output:
```
   **** Warning:  An error occurred while reading an XREF table.
   **** The file has been damaged.  This may have been caused
   **** by a problem while converting or transfering the file.
   **** Ghostscript will attempt to recover the data.
```

After this file opens in Adobe Reader, hope it helps to find the issue, or at least as a temporary fix for generated files.

**Comment by boazsegev** [comment] 2015-04-15 16:17
Thank you for opening this issue. Compatibility is an important aspect.

I installed Acrobat Reader DC for mac, but I couldn't reproduce the issue... my files were opened by the reader. Could you please provide more information?

What version of Acrobat Reader are you using?

Is the issue persistent across all files produced by combine_pdf or is it a specific file (or number of files) that cause the issue?

**Comment by yul** [comment] 2015-04-15 16:20
I think it only happens sometimes, perhaps depending on the files being merged. Can you try opening this pdf: https://dl.dropboxusercontent.com/u/3817331/service_tickets%20-%20corrupted.pdf and scroll down. I have the fresh Acrobat Reader for Windows.

**Comment by boazsegev** [comment] 2015-04-15 16:36
Thanks. I can see the corrupt file, although I cannot make one myself...

I'll start investigating and see what I can find.

**Comment by boazsegev** [comment] 2015-04-15 18:10
I commiI committed an attempted fix and I'm now releasing the updated version - could you have a look and see if the issue persists?

**Comment by yul** [comment] 2015-04-15 19:39
Wow, that was fast. Unfortunately didn't help, but I noticed that error happens when I insert several copies of one file. Maybe there is some problem with my code?
Here is how I do this:
```
      pdf = CombinePDF.new
      files.each do |file|   # files is an array of file names
        @copies.times { pdf << CombinePDF.new(file) }
        File.unlink file
      end
      pdf.save(file_name)
```

if @copies is 1, file opens in Reader, if its 3 - it doesn't. Tried it with gem version for git.

**Comment by yul** [comment] 2015-04-15 19:40
And as it happens, as soon as I posted, I noticed an error, sorry to bother ;)

**Comment by boazsegev** [comment] 2015-04-15 21:45
Thanks for narrowing down the cause for the issue.

It is now possible for me to recreate the issue and create "corrupt" pdf files... which seem to fail only on Acrobat Reader.

The only difference I can notice is the Page Tree node, which will contain duplicate Page objects (CombinePDF recognizes most duplicate objects and reduces file size by re-referencing the same object instead of writing multiple copies - a preferred PDF behavior to the best of my understanding)...

for instance, the page tree catalog (the main page tree node) on one of the PDF files I tested had the same page repeated six times:

```
<<
/Type /Pages
/Count 6 
/Kids [3 0 R 3 0 R 3 0 R 3 0 R 3 0 R 3 0 R]
>>
```

\* the 3 0 R is a reference to the page object, which is the same page 6 times.

I wonder if it's an Acrobat Reader issue or if repeating page nodes is a special case that is frowned upon...

...I'll continue investigating.

**Comment by boazsegev** [comment] 2015-04-15 22:11
Hi, I posted a new commit that resolved the issue on my machine.

This is a temporary solution that exempts Page objects from the duplication recognition and reduction process.

This will cause somewhat bigger file sizes if duplicates of the same page exist.

I still need to research this, as perhaps there is a better solution. Also, I'm very surprised by the cause... there is nothing wrong with the using references instead of actual copies... we'll see.

Could you please check this on your windows machine (I have a mac) before the updated version is released?

**Comment by yul** [comment] 2015-04-16 06:14
Yes, it works for me, thanks a lot.

**Comment by boazsegev** [comment] 2015-04-16 06:30
From what I can tell, it is a bug in Adobe Reader... but since most people work with Adobe Reader, I humbly bow my head and comply... much like I did when I was programing web apps and had to deal with IE issues, I guess.

**Closed by boazsegev** 2015-04-16 06:30 UTC
Labels: bug
